### ISSUE TITLE
Cannot iterate networks returned from conn.network.networks()

### ISSUE THREAD

**Issue by lukewallis** [nttcom/eclsdk#39]
I'm trying to list the networks using the eclsdk, however I've getting a 404 back when trying to iterate the network.networks generator. I've compared this against the openstacksdk (which is working) and the key difference is

eclsdk - Uses /networks and fails
openstacksdk - Uses /v2.0/networks and succeeds

See details below, let me know if you need any further information

**eclsdk**

1. https://keystone-de1-ecl.api.ntt.com -H "Accept: application/json" -H "User-Agent: openstacksdk/0.13.0 keystoneauth1/3.4.0 python-requests/2.19.1 CPython/2.7.15"
2. https://network-de1-ecl.api.ntt.com -H "Accept: application/json" -H "User-Agent: openstacksdk/0.13.0 keystoneauth1/3.4.0 python-requests/2.19.1 CPython/2.7.15"
3. https://network-de1-ecl.api.ntt.com/networks -H "User-Agent: openstacksdk/0.13.0 keystoneauth1/3.4.0 python-requests/2.19.1 CPython/2.7.15" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}****"

**openstacksdk**

1. https://keystone-de1-ecl.api.ntt.com -H "Accept: application/json" -H "User-Agent: openstacksdk/0.17.2 keystoneauth1/3.10.0 python-requests/2.19.1 CPython/2.7.15"
2. https://network-de1-ecl.api.ntt.com/v2.0/networks -H "Accept: application/json" -H "User-Agent: openstacksdk/0.17.2 keystoneauth1/3.10.0 python-requests/2.19.1 CPython/2.7.15" -H "X-Auth-Token: {SHA1}51080c69921e91e1227741e9206ff9b679c883f9"

**code**
```
#!/usr/bin/env python

import base64
import logging

from openstack import connection
from openstack import exceptions

logging.basicConfig(level=logging.DEBUG)

auth_args = {
        "auth_url": 'https://keystone-de1-ecl.api.ntt.com',
        "project_domain_id": 'default',
        "user_domain_id": 'default',
        "project_id": '****',
        "username": '****',
        "password": '****'
}

conn = connection.Connection(**auth_args)

networks = conn.network.networks()
for network in networks:
    print(network)
```

**output**
```
DEBUG:keystoneauth.session:REQ: curl -g -i -X GET https://network-de1-ecl.api.ntt.com -H "Accept: application/json" -H "User-Agent: openstacksdk/0.13.0 keystoneauth1/3.4.0 python-requests/2.19.1 CPython/2.7.15"
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): network-de1-ecl.api.ntt.com:443
DEBUG:urllib3.connectionpool:https://network-de1-ecl.api.ntt.com:443 "GET / HTTP/1.1" 401 28
DEBUG:keystoneauth.session:RESP: [401] Date: Wed, 12 Sep 2018 10:47:24 GMT Content-Type: text/plain; charset=utf-8 Content-Length: 28 Connection: keep-alive X-Content-Type-Options: nosniff ECL-Transaction-ID: 9bfd7e64-0aee-4b77-8afb-84a433ce775d Set-Cookie: TS0183560f=01cde22574ea4fe3f1a5cf042ad2f3a4dd53c164d1362e87ce042800faedfcf030b1ac3d7d; Path=/ 
RESP BODY: Omitted, Content-Type is set to text/plain; charset=utf-8. Only application/json responses have their bodies logged.

DEBUG:keystoneauth.session:Request returned failure status: 401
WARNING:keystoneauth.discover:Failed to contact the endpoint at https://network-de1-ecl.api.ntt.com for discovery. Fallback to using that endpoint as the base url.
DEBUG:keystoneauth.session:REQ: curl -g -i -X GET https://network-de1-ecl.api.ntt.com/networks -H "User-Agent: openstacksdk/0.13.0 keystoneauth1/3.4.0 python-requests/2.19.1 CPython/2.7.15" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}****"
DEBUG:urllib3.connectionpool:https://network-de1-ecl.api.ntt.com:443 "GET /networks HTTP/1.1" 404 19
DEBUG:keystoneauth.session:RESP: [404] Date: Wed, 12 Sep 2018 10:47:25 GMT Content-Type: text/plain; charset=utf-8 Content-Length: 19 Connection: keep-alive X-Content-Type-Options: nosniff ECL-Transaction-ID: 0f54ee76-712a-411c-9bbf-0f7b8383ebcb 
RESP BODY: Omitted, Content-Type is set to text/plain; charset=utf-8. Only application/json responses have their bodies logged.

DEBUG:openstack.task_manager:Manager defaults ran task network.GET.networks in 3.57087802887s
Traceback (most recent call last):
  File "./list-networks.py", line 23, in <module>
    for network in networks:
  File "/home/lwallis/venvs/canon/lib/python2.7/site-packages/openstack/resource.py", line 900, in list
    exceptions.raise_from_response(response)
  File "/home/lwallis/venvs/canon/lib/python2.7/site-packages/openstack/exceptions.py", line 212, in raise_from_response
    http_status=http_status, request_id=request_id
openstack.exceptions.NotFoundException: NotFoundException: 404
```

**Comment by htysh** [comment]
@lukewallis Thank you for reporting the issue.

I tried to reproduce the issue with below procedure and the latest eclsdk is working well.
```
$ pip install -U eclsdk # 0.0.8 is latest version

$ python
Python 2.7.11 (default, Jan  2 2017, 23:22:55)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from ecl import connection
>>> auth_args = {
...   "auth_url": 'https://keystone-de1-ecl.api.ntt.com',
...   "project_domain_id": 'default',
...   "user_domain_id": 'default',
...   "project_id": '***',
...   "username": '***',
...   "password": '***'
... }
>>> conn = connection.Connection(**auth_args)
>>> networks = conn.network.networks()
>>> for network in networks:
...   print network.name
...
*** # logical networks name
*** # logical networks name
>>>
```

Please let me know if the issue is not solved in spite of updating eclsdk:bow:

**Comment by lukewallis** [comment]
@htysh thanks for your support. I can see the source of my mistake quite clearly now. I was importing connection from openstack instead instead of ecl. I've corrected the line below and it's working perfectly. Apologies, I was using the example code from from the openstack website to get started

`from ecl import connection`
